### ISSUE TITLE
作者大大 这个无法获取到摄像头参数该怎么处理阿

### ISSUE THREAD

**Issue by tttjiey** [ligb888/hand-gesture#1]
2023-11-19 09:44:49,948-5833-MainProcess-INFO-main.py[:49]-读取配置完成
2023-11-19 09:44:49,958-5833-MainProcess-INFO-simulate.py[:48]-屏幕分辨率：1920.0,1080.0
2023-11-19 09:44:49,958-5833-MainProcess-INFO-simulate.py[:49]-摄像头分辨率：0,0
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2023-11-19 09:44:52,763-5833-MainProcess-INFO-main.py[:53]-读取配置出错：Traceback (most recent call last):
  File "/home/t/桌面/hand-gesture-master/main.py", line 51, in <module>
    control.recognize(cap_width, cap_height, cap_fps, cap_flip, crop1, crop2, smooth)
  File "/home/t/桌面/hand-gesture-master/src/simulate.py", line 54, in recognize
    exit()
  File "/home/t/conda/envs/my_paddlex/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by ligb888** [comment]
配置里的index参数是配置摄像头索引的，如果是本机摄像头一般是0、1、2这样的顺序。你可以先使用一些软件查看自己的摄像头是否正常。然后可以通过一些代码打印出所有的摄像头索引

**Comment by floatingdev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

marshal2004, @williamHappy, @SnowyThinker, @ZinniaSun2000, @lindadev77, @SullenQuinlan, @alvin-kun, @myt2000, @fishear, @HuanYeMengYu, @zestzone007, @t0591, @coo-lfish, @fyx200013, @suixinio, @Jennywho-Hu, @hydcoder, @TroubledPhilip, @Yeuman, @kevinweb3
